# Generated by Django 5.1.4 on 2025-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profilePicture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
