# Generated by Django 5.1.4 on 2025-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.CharField(default='Your Description', max_length=1000),
        ),
    ]
