# Generated by Django 5.1.4 on 2025-03-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Categories0',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('category0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizAPI.category0')),
            ],
            options={
                'verbose_name_plural': 'Categories1',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizAPI.question')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_file',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('questions_file', models.FileField(upload_to='quiz/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizAPI.category0')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizAPI.category1')),
            ],
            options={
                'verbose_name_plural': 'questions_file',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questions_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizAPI.questions_file'),
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('questions_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_category', to='quizAPI.questions_file')),
            ],
            options={
                'verbose_name_plural': 'SubjectCategories',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizAPI.subjectcategory'),
        ),
    ]
