# Generated by Django 5.1.4 on 2025-03-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizAPI', '0002_questions_file_updated_at_quizresult'),
        ('quizAPI', '0003_leaderboard_userquizresult_userresponse_and_more'),
    ]

    operations = [
    ]
