# Generated by Django 5.1.4 on 2025-04-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizAPI', '0003_leaderboard_userquizresult_userresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_file',
            name='category0',
        ),
        migrations.RemoveField(
            model_name='category1',
            name='category0',
        ),
        migrations.RemoveField(
            model_name='questions_file',
            name='category1',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('level', models.PositiveBigIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quizAPI.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='questions_file',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_files', to='quizAPI.category'),
        ),
        migrations.DeleteModel(
            name='Category0',
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
