# Generated by Django 5.1.4 on 2025-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizAPI', '0004_merge_20250331_1008'),
        ('quizAPI', '0005_image'),
    ]

    operations = [
    ]
