# Generated by Django 5.1.4 on 2025-04-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizAPI', '0006_merge_0004_merge_20250331_1008_0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_file',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
